version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zoo1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    depends_on:
      - kafka
      - zoo1
    ports:
      - "9000:9000"
    links:
      - zoo1
      - kafka
    environment:
      ZK_HOSTS: zoo1:2181
      KM_ARGS: -Djava.net.preferIPv4Stack=true